### ISSUE TITLE
Сreate a design for navigation in the site menu

### ISSUE THREAD

**Issue by marysergey** [easably/www#17]
For example
![11](https://user-images.githubusercontent.com/47523695/53336731-44521200-3910-11e9-8fab-40dbafb2f087.png)

**Comment by AnastasiyaFyodor** [comment]
<img width="775" alt="screen shot 2019-02-25 at 16 20 10" src="https://user-images.githubusercontent.com/47668201/53340217-83389580-3919-11e9-9f48-ef2267b48737.png">
