### ISSUE TITLE
Landing Design

### ISSUE THREAD

**Issue by marysergey** [easably/www#2]
please upload all images for landing page here

**Comment by AnastasiyaFyodor** [comment]
![1page](https://user-images.githubusercontent.com/47668201/52865944-baa38700-314e-11e9-8c9f-aa99c2595f84.png)
![2page](https://user-images.githubusercontent.com/47668201/52865945-baa38700-314e-11e9-98be-d5dc1a412c7a.png)
![3page](https://user-images.githubusercontent.com/47668201/52865946-baa38700-314e-11e9-9f2e-588fa251bcb8.png)

**Comment by AnastasiyaFyodor** [comment]
![1page](https://user-images.githubusercontent.com/47668201/52867523-2c310480-3152-11e9-8e01-c762fa83bef6.png)
![1page](https://user-images.githubusercontent.com/47668201/52867549-3d7a1100-3152-11e9-93a9-e663f6b5ff99.jpg)

**Comment by AnastasiyaFyodor** [comment]
![2page](https://user-images.githubusercontent.com/47668201/52867730-9cd82100-3152-11e9-9769-54f0aba79eeb.png)
![2page](https://user-images.githubusercontent.com/47668201/52867769-afeaf100-3152-11e9-99c3-c1f79b8ec7f2.jpg)

**Comment by AnastasiyaFyodor** [comment]
![3page](https://user-images.githubusercontent.com/47668201/52867831-d3ae3700-3152-11e9-8dd7-958620613952.png)
![3page](https://user-images.githubusercontent.com/47668201/52867833-d4df6400-3152-11e9-8a30-a251b99002b8.jpg)

**Comment by AnastasiyaFyodor** [comment]
Сначала png, потом jpg

**Comment by marysergey** [comment]
[prototype](https://startbootstrap.com/previews/landing-page/)
