### ISSUE TITLE
Create a screen flow for the task #21

### ISSUE THREAD

**Issue by marysergey** [easably/www#22]
Create a screen flow for the task 
https://github.com/easably/www/issues/21
on the example of these screenshots

![1](https://user-images.githubusercontent.com/47523695/53479187-85216680-3a89-11e9-8df8-058a201325a4.png)
action on click
![2](https://user-images.githubusercontent.com/47523695/53479190-86529380-3a89-11e9-82e7-c5b5b21345b4.png)

Take [this icon](https://cdn0.iconfinder.com/data/icons/miscellaneous-35/100/misc-29-512.png)
Our languages are only Russian and English.

**Comment by AnastasiyaFyodor** [comment]
<img width="407" alt="screen shot 2019-02-27 at 13 29 15" src="https://user-images.githubusercontent.com/47668201/53484034-ea7a5500-3a93-11e9-95ca-bd9090cec680.png">

**Comment by marysergey** [comment]
@alla-cherniauskaya please take it for #21
