### ISSUE TITLE
Need to fix grammatical errors in the img

### ISSUE THREAD

**Issue by marysergey** [easably/www#23]
![crhby](https://user-images.githubusercontent.com/47523695/53485793-38915780-3a98-11e9-9f60-f87e4678008c.png)

Milky Way
Universe

**Comment by AnastasiyaFyodor** [comment]
![2](https://user-images.githubusercontent.com/47668201/53486310-6d51de80-3a99-11e9-87ce-2ade7353f239.jpg)
@alla done

**Comment by marysergey** [comment]
@alla-cherniauskaya change image on the landing page

**Comment by AnastasiyaFyodor** [comment]
![Uploading Screen Shot 2019-03-12 at 15.05.17.png…]()

**Comment by AnastasiyaFyodor** [comment]
<img width="512" alt="Screen Shot 2019-03-12 at 15 05 17" src="https://user-images.githubusercontent.com/47668201/54198756-57e8a580-44d8-11e9-9a8a-c553aea38dd9.png">
