### ISSUE TITLE
Create communication scheme 

### ISSUE THREAD

**Issue by marysergey** [easably/www#25]
![screenshot_1](https://user-images.githubusercontent.com/47523695/53568021-f9373980-3b71-11e9-9e71-4214b4716993.png)

**Comment by AnastasiyaFyodor** [comment]
<img width="851" alt="screen shot 2019-02-28 at 18 20 30" src="https://user-images.githubusercontent.com/47668201/53576852-a49db980-3b85-11e9-9f3a-afb42d27eb20.png">
<img width="830" alt="screen shot 2019-02-28 at 18 20 39" src="https://user-images.githubusercontent.com/47668201/53576853-a49db980-3b85-11e9-98a5-9aeac27634f2.png">

**Comment by marysergey** [comment]
@AnastasiyaFyodor please make another version in another color

**Comment by marysergey** [comment]
"Broadcast media information" written twice
@AnastasiyaFyodor Fix it, please

**Comment by AnastasiyaFyodor** [comment]
<img width="868" alt="screen shot 2019-03-07 at 16 13 12" src="https://user-images.githubusercontent.com/47668201/53959159-ee415380-40f3-11e9-9ca9-d52e29944143.png">
<img width="811" alt="screen shot 2019-03-07 at 16 05 59" src="https://user-images.githubusercontent.com/47668201/53959161-eed9ea00-40f3-11e9-8a8a-fa161ea341d7.png">

**Comment by AnastasiyaFyodor** [comment]
<img width="619" alt="Screen Shot 2019-03-13 at 13 33 49" src="https://user-images.githubusercontent.com/47668201/54272457-ca1ec000-4594-11e9-8cc7-7b46d497988c.png">
