### ISSUE TITLE
Create a horizontal scheme

### ISSUE THREAD

**Issue by marysergey** [easably/www#26]
![screenshot_2](https://user-images.githubusercontent.com/47523695/53568022-f9cfd000-3b71-11e9-8d61-19cac105d467.png)

**Comment by AnastasiyaFyodor** [comment]
<img width="849" alt="screen shot 2019-03-01 at 13 52 43" src="https://user-images.githubusercontent.com/47668201/53633822-95704780-3c29-11e9-8dad-82f8f0816ba0.png">
<img width="872" alt="screen shot 2019-03-01 at 13 52 57" src="https://user-images.githubusercontent.com/47668201/53633823-9608de00-3c29-11e9-8897-6a8db49da1be.png">
Возможно, я что-то не правильно в тексте поняла и написала не так. Скажите, исправлю)

**Comment by marysergey** [comment]
@AnastasiyaFyodor add a prototype image as close as possible to the attachment in the task. Because what you added to this comment relates to this https://github.com/easably/www/issues/28

**Comment by AnastasiyaFyodor** [comment]
<img width="859" alt="Screen Shot 2019-03-13 at 12 16 43" src="https://user-images.githubusercontent.com/47668201/54267305-07318500-458a-11e9-8a21-2232a3d62617.png">
