### ISSUE TITLE
Make a prototype image

### ISSUE THREAD

**Issue by marysergey** [easably/www#27]
![screenshot_7](https://user-images.githubusercontent.com/47523695/53632414-ec741d80-3c25-11e9-9172-b7785efca4a6.png)

**Comment by AnastasiyaFyodor** [comment]
<img width="738" alt="screen shot 2019-03-01 at 17 54 41" src="https://user-images.githubusercontent.com/47668201/53645963-20ae0500-3c4b-11e9-8225-b4929968754e.png">

**Comment by AnastasiyaFyodor** [comment]
<img width="674" alt="screen shot 2019-03-01 at 17 59 47" src="https://user-images.githubusercontent.com/47668201/53646279-da0cda80-3c4b-11e9-91d3-a1557881b4dd.png">
