### ISSUE TITLE
Text for landing

### ISSUE THREAD

**Issue by marysergey** [easably/www#3]
### The text is presented in Russian and English.

**EasyLang
Discover the universe of information in any language!**

EasyLang
Откройте для себя вселенную информации на иностранном языке!

**Choose Your Favorite**
Выбирайте любимую тематику
**Make a choice according to your interests**
Сделайте упор на информацию, которая вам интересна
**Our software allows you to learn the language not only in the text and on today's news, but also in video subtitles. You can choose what is closer and more interesting for you or combine all the ways of learning!**
Наше программное обеспечение позволяет изучать язык не только в тексте, книжных изданиях и новостях, но и в видео с помощью субтитров. Вы можете выбрать то, что вам ближе и интереснее, или объединить все способы обучения!

**Reach It**
Достигайте ощутимых результатов
**You have the power to more deeply learn any language**
Ваша сила в возможности глубже изучить любой язык
**The universe is infinite, like information that appears every day. Build your knowledge base, check yourself, follow the progress of this flight and improve your skills! Our software mechanics open the way to a deeper understanding of the material. Select a word and look for synonyms or synonym constructions with various explanations at the same time.**
Вселенная бесконечна, как и информация, которая ежедневно появляется, расширяя свои бескрайние просторы. Создайте свою базу знаний, проверяйте себя, следите за прогрессом этого полета и улучшайте свои навыки! Механика нашего программного обеспечения открывает путь к более глубокому пониманию материала. Выберите слово и находите его синонимы с различными толкованиями.

**Trust Your Memory**
Доверьтесь своей памяти
**Now you can easier remember the information**
Теперь Вы можете намного легче запоминать информацию
**A unique tutor allows you to literally resurrect the word from your memory. We show exactly the context in which the acquaintance between you and a particular word occurred. It helps you remember it quickly and for a long time.**
Уникальный помощник позволяет буквально воскресить слово из вашей памяти. Мы показываем именно тот контекст, в котором произошло знакомство между вами и тем самым словом. Это поможет вам запомнить его быстро и, что не менее важно, надолго.

**You can study easily without losing interest!**
Вы можете учиться легко, не теряя интереса!

**Comment by alla-cherniauskaya** [comment]
text for landing page already changed
