### ISSUE TITLE
icons for landing

### ISSUE THREAD

**Issue by marysergey** [easably/www#4]
provide your own previously drawn icons
upload images in this issue

**Comment by marysergey** [comment]
alternative version

https://fontawesome.com/v4.7.0/icon/heart

https://fontawesome.com/v4.7.0/icon/star-o

https://fontawesome.com/v4.7.0/icon/thumbs-o-up

**Comment by AnastasiyaFyodor** [comment]
![default](https://user-images.githubusercontent.com/47668201/52961888-005d8b00-33ad-11e9-8589-b35403b25a59.png)

![default](https://user-images.githubusercontent.com/47668201/52961851-eb80f780-33ac-11e9-9b65-896c492d4f07.png)
![default](https://user-images.githubusercontent.com/47668201/52961852-eb80f780-33ac-11e9-8d08-e04e1df77670.png)
