### ISSUE TITLE
top img for landing

### ISSUE THREAD

**Issue by marysergey** [easably/www#5]
Please create an image for the top (1900/1216) and bottom of the landing page

preferably black sky with stars according to the color scheme of the subsequent drawings

**Comment by AnastasiyaFyodor** [comment]
![top page](https://user-images.githubusercontent.com/47668201/52949419-44d92e80-338d-11e9-93b3-07cdc24a6172.png)

**Comment by marysergey** [comment]
what about the image at the underside of the page? @AnastasiyaFyodor
