### ISSUE TITLE
Create design on page 404

### ISSUE THREAD

**Issue by marysergey** [easably/www#8]
http://sytycdism.com/page-not-found.html - examples

Create a design for the page that will display 404

I propose to depict an astronaut in space
Astronaut says "oh no ... page not found"

**Comment by marysergey** [comment]
@AnastasiyaFyodor please inform @BelkevichAndry  when you finish it

Please use the Githab comments

**Comment by AnastasiyaFyodor** [comment]
![404landing](https://user-images.githubusercontent.com/47668201/53348018-52f9f280-392b-11e9-870f-cc384af23977.png)
